#!/usr/bin/env bun

import { $ } from "bun"
import fs from "fs"
import path from "path"
import { fileURLToPath } from "url"
import { createSolidTransformPlugin } from "@opentui/solid/bun-plugin"
import { ALL_TARGETS as allTargets, filterTargets, targetName } from "./targets.ts"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

await import("./generate.ts")

import { Script } from "@mimo-ai/script"
import pkg from "../package.json"

const BINARY_PREFIX = "oimo"

// Load migrations from migration directories
const migrationDirs = (
  await fs.promises.readdir(path.join(dir, "migration"), {
    withFileTypes: true,
  })
)
  .filter((entry) => entry.isDirectory() && /^\d{4}\d{2}\d{2}\d{2}\d{2}\d{2}/.test(entry.name))
  .map((entry) => entry.name)
  .sort()

const migrations = await Promise.all(
  migrationDirs.map(async (name) => {
    const file = path.join(dir, "migration", name, "migration.sql")
    const sql = await Bun.file(file).text()
    const match = /^(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})/.exec(name)
    const timestamp = match
      ? Date.UTC(
          Number(match[1]),
          Number(match[2]) - 1,
          Number(match[3]),
          Number(match[4]),
          Number(match[5]),
          Number(match[6]),
        )
      : 0
    return { sql, timestamp, name }
  }),
)
console.log(`Loaded ${migrations.length} migrations`)

const singleFlag = process.argv.includes("--single")
const baselineFlag = process.argv.includes("--baseline")
const skipInstall = process.argv.includes("--skip-install")
const plugin = createSolidTransformPlugin()
// const skipEmbedWebUi = process.argv.includes("--skip-embed-web-ui")
// Web UI temporarily disabled
const skipEmbedWebUi = true

const createEmbeddedWebUIBundle = async () => {
  console.log(`Building Web UI to embed in the binary`)
  const appDir = path.join(import.meta.dirname, "../../app")
  const dist = path.join(appDir, "dist")
  await $`bun run --cwd ${appDir} build`
  const files = (await Array.fromAsync(new Bun.Glob("**/*").scan({ cwd: dist })))
    .map((file) => file.replaceAll("\\", "/"))
    .sort()
  const imports = files.map((file, i) => {
    const spec = path.relative(dir, path.join(dist, file)).replaceAll("\\", "/")
    return `import file_${i} from ${JSON.stringify(spec.startsWith(".") ? spec : `./${spec}`)} with { type: "file" };`
  })
  const entries = files.map((file, i) => `  ${JSON.stringify(file)}: file_${i},`)
  return [
    `// Import all files as file_$i with type: "file"`,
    ...imports,
    `// Export with original mappings`,
    `export default {`,
    ...entries,
    `}`,
  ].join("\n")
}

const embeddedFileMap = skipEmbedWebUi ? null : await createEmbeddedWebUIBundle()
const treeSitterWorker = await Bun.file(fileURLToPath(import.meta.resolve("@opentui/core/parser.worker"))).text()

const targetFilter = (process.env.MIMOCODE_TARGETS ?? "")
  .split(",")
  .map((t) => t.trim())
  .filter(Boolean)

const targets = singleFlag
  ? allTargets.filter((item) => {
      if (item.os !== process.platform || item.arch !== process.arch) {
        return false
      }

      // When building for the current platform, prefer a single native binary by default.
      // Baseline binaries require additional Bun artifacts and can be flaky to download.
      if (item.avx2 === false) {
        return baselineFlag
      }

      // also skip abi-specific builds for the same reason
      if (item.abi !== undefined) {
        return false
      }

      return true
    })
  : filterTargets(allTargets, targetFilter)

await $`rm -rf dist`

const extDir = path.join(dir, "src", "ext")
let stagedExt = false
if (!fs.existsSync(extDir)) {
  const overlaySrc = path.resolve(dir, "../../mimoapi/packages/opencode/src/ext")
  if (fs.existsSync(overlaySrc)) {
    console.log(`Staging overlay entrypoints from ${overlaySrc}`)
    fs.cpSync(overlaySrc, extDir, { recursive: true })
    stagedExt = true
  }
}
// Emit a manifest with a fixed import path so runtime loaders resolve src/ext
// modules from the dependency graph rather than scanning the filesystem, which
// does not work inside Bun single-file executables. The manifest is empty when
// src/ext has no modules.
const createdExtDir = !fs.existsSync(extDir)
if (createdExtDir) fs.mkdirSync(extDir, { recursive: true })
const extFiles = fs
  .readdirSync(extDir)
  .filter((f) => f.endsWith(".ts") && !f.endsWith(".d.ts") && f !== "_manifest.ts")
  .sort()
const manifestImports = extFiles.map((f, i) => `import * as m${i} from "./${f.replace(/\.ts$/, "")}"`).join("\n")
const manifestEntries = extFiles.map((f, i) => `  ["${f.replace(/\.ts$/, "")}", m${i}],`).join("\n")
fs.writeFileSync(
  path.join(extDir, "_manifest.ts"),
  `// Generated by script/build.ts. Do not edit.\n${manifestImports}\nexport const modules: Record<string, Record<string, unknown>> = Object.fromEntries([\n${manifestEntries}\n])\n`,
)
if (extFiles.length) console.log(`Including overlay entrypoints: ${extFiles.map((f) => `./src/ext/${f}`).join(", ")}`)
process.on("exit", () => {
  try {
    if (stagedExt || createdExtDir) fs.rmSync(extDir, { recursive: true, force: true })
    else fs.rmSync(path.join(extDir, "_manifest.ts"), { force: true })
  } catch {}
})

const binaries: Record<string, string> = {}
if (!skipInstall) {
  await $`bun install --os="*" --cpu="*" @opentui/core@${pkg.dependencies["@opentui/core"]}`
  await $`bun install --os="*" --cpu="*" @parcel/watcher@${pkg.dependencies["@parcel/watcher"]}`
}
for (const item of targets) {
  const name = targetName(item)
  console.log(`building ${name}`)
  await $`mkdir -p dist/${name}/bin`

  const workerPath = "./src/cli/cmd/tui/worker.ts"
  const treeSitterWorkerPath = "opentui-tree-sitter-worker.js"

  // Use platform-specific bunfs root path based on target OS
  const bunfsRoot = item.os === "win32" ? "B:/~BUN/root/" : "/$bunfs/root/"

  await Bun.build({
    conditions: ["browser"],
    tsconfig: "./tsconfig.json",
    plugins: [plugin],
    external: ["node-gyp"],
    format: "esm",
    minify: true,
    splitting: true,
    compile: {
      autoloadBunfig: false,
      autoloadDotenv: false,
      autoloadTsconfig: true,
      autoloadPackageJson: true,
      target: name.replace(BINARY_PREFIX, "bun") as any,
      outfile: `dist/${name}/bin/oimo`,
      execArgv: [`--user-agent=oimo/${Script.version}`, "--use-system-ca", "--"],
      windows: {},
    },
    files: {
      [treeSitterWorkerPath]: treeSitterWorker,
      ...(embeddedFileMap ? { "opencode-web-ui.gen.ts": embeddedFileMap } : {}),
    },
    entrypoints: [
      "./src/index.ts",
      workerPath,
      treeSitterWorkerPath,
      ...(embeddedFileMap ? ["opencode-web-ui.gen.ts"] : []),
    ],
    define: {
      MIMOCODE_VERSION: `'${Script.version}'`,
      OPENCODE_MIGRATIONS: JSON.stringify(migrations),
      OTUI_TREE_SITTER_WORKER_PATH: bunfsRoot + treeSitterWorkerPath,
      OPENCODE_WORKER_PATH: workerPath,
      MIMOCODE_CHANNEL: `'${Script.channel}'`,
      OPENCODE_LIBC: item.os === "linux" ? `'${item.abi ?? "glibc"}'` : "",
      ...(item.os === "linux" ? { "process.env.OPENTUI_LIBC": JSON.stringify(item.abi ?? "glibc") } : {}),
    },
  })

  // Smoke test: only run if binary is for current platform
  if (item.os === process.platform && item.arch === process.arch && !item.abi) {
    const binaryPath = `dist/${name}/bin/oimo`
    console.log(`Running smoke test: ${binaryPath} --version`)
    try {
      const versionOutput = await $`${binaryPath} --version`.text()
      console.log(`Smoke test passed: ${versionOutput.trim()}`)
    } catch (e) {
      console.error(`Smoke test failed for ${name}:`, e)
      process.exit(1)
    }
  }

  await $`rm -rf ./dist/${name}/bin/tui`
  await Bun.file(`dist/${name}/README.md`).write(
    `This is the ${item.os}-${item.arch} binary for [@mimo-ai/cli](https://www.npmjs.com/package/@mimo-ai/cli). Install that package directly.\n`,
  )
  await Bun.file(`dist/${name}/package.json`).write(
    JSON.stringify(
      {
        name: `@mimo-ai/${name}`,
        version: Script.version,
        description: "Platform-specific binary for @mimo-ai/cli.",
        license: "MIT",
        author: "Open Open Mimo Code Team",
        homepage: "https://github.com/kuwa2005/oimo",
        repository: {
          type: "git",
          url: "git+https://github.com/kuwa2005/oimo.git",
        },
        keywords: ["ai", "coding", "agent", "cli", "mimo"],
        os: [item.os],
        cpu: [item.arch],
      },
      null,
      2,
    ),
  )
  binaries[name] = Script.version
}

if (Script.release) {
  for (const key of Object.keys(binaries)) {
    if (key.includes("linux")) {
      await $`tar -czf ../../${key}.tar.gz *`.cwd(`dist/${key}/bin`)
    } else {
      await $`zip -r ../../${key}.zip *`.cwd(`dist/${key}/bin`)
    }
  }
  const archives = fs
    .readdirSync("dist")
    .filter((f) => f.endsWith(".zip") || f.endsWith(".tar.gz"))
    .map((f) => `dist/${f}`)
  const uploads = [...archives]
  if (targetFilter.length === 0) {
    // Full build: emit a single aggregate SHA256SUMS. Matrix runs skip this;
    // the publish job regenerates it from the uploaded assets (spec R3).
    const { sha256Sums } = await import("../../../script/checksums.ts")
    const sumsFile = "dist/SHA256SUMS"
    await Bun.file(sumsFile).write(await sha256Sums(archives))
    uploads.push(sumsFile)
  }
  // MIMOCODE_SKIP_UPLOAD=1 (tag-triggered release.yml matrix): build archives
  // only; the release does not exist yet, so assemble uploads them via
  // actions/upload-artifact and softprops/action-gh-release.
  if (!process.env.MIMOCODE_SKIP_UPLOAD) {
    await $`gh release upload v${Script.version} ${uploads} --clobber --repo ${process.env.GH_REPO}`
  }

  // Also publish to Xiaomi FDS (fast download in mainland China). Skipped when
  // credentials are absent so local release builds still work. The install
  // scripts download from GitHub by default and can be pointed at a mirror
  // (e.g. the FDS CDN) via OIMO_BASE_URL.
  if (process.env.MIMO_FDS_AK && process.env.MIMO_FDS_SK) {
    const { uploadFile } = await import("./fds-upload.ts")
    const archives = fs
      .readdirSync("dist")
      .filter((f) => f.endsWith(".zip") || f.endsWith(".tar.gz") || f === "SHA256SUMS")
    for (const file of archives) {
      await uploadFile(`dist/${file}`, `releases/v${Script.version}/${file}`)
      console.log(`Uploaded to FDS: releases/v${Script.version}/${file}`)
    }
    const tmpLatest = "dist/_latest.txt"
    await Bun.write(tmpLatest, Script.version)
    await uploadFile(tmpLatest, "releases/latest", "text/plain")
    console.log(`Uploaded to FDS: releases/latest -> ${Script.version}`)
  } else {
    console.log("Skipping FDS upload (MIMO_FDS_AK / MIMO_FDS_SK not set)")
  }
}

export { binaries }
